# PostgreSQL JDBC driver
driver=org.postgresql.Driver

# Connection URL (SSL disabled)
url=jdbc:postgresql://db:5432/demodb?sslmode=disable

# Credentials
username=myuser
password=demoPa5s!

# Liquibase settings
changeLogFile=master-changelog.yaml
logLevel=info
