name: Compose
description: location for the Docker compose file

configuration:
  file:
    required: false
    type: string
    default: infrastructure/docker-compose.yaml
    description: default location for the Docker compose file
